"""empty message

Revision ID: ef45e44c7a25
Revises: 2b2b7189e84b
Create Date: 2021-05-03 15:27:25.236076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef45e44c7a25'
down_revision = '2b2b7189e84b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comet', sa.Column('cult_following', sa.String(), nullable=True))
    op.add_column('comet', sa.Column('size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comet', 'size')
    op.drop_column('comet', 'cult_following')
    # ### end Alembic commands ###
